const { createServiceClient } = await import("../../src/lib/supabase/service");
const db = createServiceClient();
const CO = "5925c03a-557f-46d7-8589-7388b769df40";
const { data: raw } = await db.from("company_employees").select("*").eq("company_id", CO);
console.log(`권혁수 회사의 자리: ${raw?.length ?? 0}개`);
for (const r of (raw ?? []) as Record<string, unknown>[]) console.log(`  ${JSON.stringify(r).slice(0,160)}`);
const { data: demo } = await db.from("company_employees").select("*").eq("id", "e660c68b-5cdf-47ba-9673-5dded5cb8d83").maybeSingle();
console.log(`데모의 Dev 자리 칸: ${Object.keys((demo ?? {}) as object).join(", ")}`);
console.log(`  ${JSON.stringify(demo).slice(0,220)}`);
const { data: cnt } = await db.from("assignments").select("id", { count: "exact", head: true }).eq("company_id", CO);
console.log(`권혁수 회사의 일 개수: ${JSON.stringify(cnt)}`);
